export const els = {};

export function cacheElements() {
  Object.assign(els, {
    bookList: document.querySelector('#book-list'),
    chapterKicker: document.querySelector('#chapter-kicker'),
    chapterTitle: document.querySelector('#chapter-title'),
    passage: document.querySelector('#passage'),
    typingSurface: document.querySelector('#typing-surface'),
    mobileCapture: document.querySelector('#mobile-capture'),
    typingHelp: document.querySelector('#typing-help'),
    typingProgressFill: document.querySelector('#typing-progress-fill'),
    typingProgress: document.querySelector('#typing-progress'),
    characterCount: document.querySelector('#character-count'),
    accuracyValue: document.querySelector('#accuracy-value'),
    timeValue: document.querySelector('#time-value'),
    liveWpm: document.querySelector('#live-wpm'),
    liveAvgWpm: document.querySelector('#live-avg-wpm'),
    toast: document.querySelector('#toast'),
    epubInput: document.querySelector('#epub-input'),
    uploadDropzone: document.querySelector('#upload-dropzone'),
    fileDropOverlay: document.querySelector('#file-drop-overlay'),
    resetButton: document.querySelector('#reset-button'),
    practiceView: document.querySelector('#practice-view'),
    statsView: document.querySelector('#stats-view'),
    settingsView: document.querySelector('#settings-view'),
    charsetPreset: document.querySelector('#charset-preset'),
    charsetInput: document.querySelector('#charset-input'),
    bestWpm: document.querySelector('#best-wpm'),
    averageAccuracy: document.querySelector('#average-accuracy'),
    sessionsFinished: document.querySelector('#sessions-finished'),
    charactersTyped: document.querySelector('#characters-typed'),
    statsChart: document.querySelector('#stats-chart'),
    statsChartEmpty: document.querySelector('#stats-chart-empty'),
    chapterResults: document.querySelector('#chapter-results'),
    chapterResultsTitle: document.querySelector('#chapter-results-title'),
    resultsWpm: document.querySelector('#results-wpm'),
    resultsEmaWpm: document.querySelector('#results-ema-wpm'),
    resultsAccuracy: document.querySelector('#results-accuracy'),
    resultsTime: document.querySelector('#results-time'),
    chapterSpeedChart: document.querySelector('#chapter-speed-chart'),
    chapterAccuracyChart: document.querySelector('#chapter-accuracy-chart'),
    chapterResultsClose: document.querySelector('#chapter-results-close'),
    chapterResultsNext: document.querySelector('#chapter-results-next'),
    resetSettings: document.querySelector('#reset-settings')
  });
}
